### ISSUE TITLE
Will this be published on npm?

### ISSUE THREAD

**Issue by acheronfail** [parkertomatoes/fatfs-wasm#1]
Hey there! 

I've been looking into implementing something with the exact same setup as this package, and was very happy to find this repository. I was wondering if you had plans to publish this to npm? I can't find it there right now, [only a 404 for `fatfs-wasm`](https://www.npmjs.com/package/fatfs-wasm).

~~I also found https://github.com/irori/js-fatfs, but the API exposed in this repository seems more ergomonic from a package consumer point of view (the errors are handled in each method in this module, but in the other one must be handled explicitly).~~ In the meantime I've begun using this one, since it also has LFN support which is something I required!

**Comment by parkertomatoes** [comment]
Sorry for the long delay, I published it to npm.
